name: doc-deployment
on:
  pull_request:
    branches:
      - master

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ¡ Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "ğŸ Install python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: "ğŸ’Œ Install Poetry"
        uses: snok/install-poetry@v1
      - name: "ğŸ§± Install patentcity dependencies"
        run: poetry install
      - name: "ğŸ“š Deploy doc"
        run: |
          poetry install --only doc
          poetry run mkdocs gh-deploy
