name: requirements-code-quality
on:
  pull_request:
    branches:
      - master
      - nightly
jobs:
  check-requirements-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ¡ Checkout repository"
        uses: actions/checkout@v3
      - name: "ğŸ Install python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.8" 
      - name: "ğŸ’Œ Install Poetry"
        uses: snok/install-poetry@v1
      - name: "ğŸ§± Check install patentcity dependencies"
        run: poetry install
      - name: "ğŸ¨ Linting checks"
        run: |
          poetry install --only linting
          poetry run black --check patentcity/
          poetry run isort --check patentcity/
          poetry run pylint patentcity/
